name: torch
channels:
  - pytorch
  - conda-forge
dependencies:
  - conda-forge::python=3.10.15
  - pytorch=2.3.1
  - setuptools=59.5.0
  - numpy=1.23.5
  - coffea=0.7.22
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
